language: go

go: 1.13.x

services:
  - docker

cache:
  directories:
    - $GOPATH/pkg/mod

env:
  global:
    - GO111MODULE=on

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0
  - go mod download

script:
  - golangci-lint run ./...
  - go test -v -race -cover ./...
